### ISSUE TITLE
Problem with npm! 

### ISSUE THREAD

**Issue by iagocavalcante** [Amimaro/repy#1]
When i try to run the script, the script install first package and close the cmd.

**Comment by osamuca** [comment]
@iagocavalcante as well?

**Comment by Amimaro** [comment]
Thanks @iagocavalcante !
I believe this problem was occurring with Windows batch files.
The problem may be related to the batch file executing another batch file that caused the parent batch program to stop.
The solution was to add the [CALL](https://ss64.com/nt/call.html) command before each npm command.
Tests are being conducted to verify that this same problem occurs in other operating systems.
